create DATABASE rest_app_db;

CREATE TABLE person(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar (100) NOT NULL,
    age int check (age>0) NOT NULL,
    email varchar(100) NOT NULL
);

alter table person add column created_at timestamp ,
add column updated_at timestamp,
add column created_who varchar;
